### ISSUE TITLE
Undefined index url_api

### ISSUE THREAD

**Issue by Ezyweb-uk** [microweber-modules/schema-org#2]
Laravel log error: 
Undefined index: url_api {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined index: url_api at userfiles\modules\schema-org\functions.php:28)

Also can't see anyway to uninstall this module via admin.

**Comment by peter-mw** [comment]
fixed

**Comment by Ezyweb-uk** [comment]
Peter, url_api also referenced on line 39

**Comment by Ezyweb-uk** [comment]
Seems to be fixed now when tested in dev branch.
